### PR TITLE
add additional unit tests for long JWTs

### PR DESCRIPTION
**Pull request by nareddyt**
Verification that long claims are still decoded and verified successfully

### CODE REVIEW

**Comment by TAOXUY** [comment]
Could you provide some context? Why we need to test these?

**Comment by nareddyt** [comment]
> Could you provide some context? Why we need to test these?

Trying to debug b/271292995. There are no tests in the repo for long JWTs so adding them for future reference.

**Comment by TAOXUY** [comment]
Comment the length limit are tested against in these test cases?

**Review by TAOXUY — APPROVED** [review]

**Comment by nareddyt** [comment]
> Comment the length limit are tested against in these test cases?

Added extra comment describing length. Keep in mind the test case name already mentions this

**Pull request merged**
